# Autogenerated by devscripts/update-version.py

__version__ = '2023.11.27.195425'

RELEASE_GIT_HEAD = '0de7b539db637a5352eff38b6a030a3082309f0e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stanrb/yt-dlp'

ORIGIN = 'stanrb/yt-dlp'

_pkg_version = '2023.11.27.195425'
